# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Check  Types

on:
  push:
    branches: ['*']

jobs:
  check-types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 'latest'
          cache: 'npm'
      - name: npm clean install
        run: npm ci
      - run: node --run types:check
